#ifndef UECC_CONFIG_H
#define UECC_CONFIG_H

#define uECC_SUPPORTS_secp160r1 0
#define uECC_SUPPORTS_secp192r1 0
#define uECC_SUPPORTS_secp224r1 0
#define uECC_SUPPORTS_secp256r1 1
#define uECC_SUPPORTS_secp256k1 0

#define uECC_SUPPORT_COMPRESSED_POINT 0

#define uECC_OPTIMIZATION_LEVEL 2

#endif /* UECC_CONFIG_H */
