// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectNAT() {
  return window['go']['main']['App']['DetectNAT']();
}

export function DiscoverSwitches() {
  return window['go']['main']['App']['DiscoverSwitches']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function OpenNpssoPage() {
  return window['go']['main']['App']['OpenNpssoPage']();
}

export function OpenPsnLogin() {
  return window['go']['main']['App']['OpenPsnLogin']();
}

export function PushToSwitch(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushToSwitch'](arg1, arg2, arg3);
}

export function RegenerateDUID() {
  return window['go']['main']['App']['RegenerateDUID']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
