// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {pair} from '../models';

export function DetectNAT():Promise<backend.NatInfo>;

export function DiscoverSwitches():Promise<Array<pair.SwitchInfo>>;

export function Login(arg1:string):Promise<backend.Status>;

export function OpenNpssoPage():Promise<void>;

export function OpenPsnLogin():Promise<void>;

export function PushToSwitch(arg1:string,arg2:number,arg3:string):Promise<backend.PushOutcome>;

export function RegenerateDUID():Promise<backend.Status>;

export function Status():Promise<backend.Status>;
